# These are supported funding model platforms

github: castarco
patreon: coder_spirit
open_collective: # Replace with a single Open Collective username
ko_fi: coderspirit
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: castarco
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: https://www.paypal.com/donate?hosted_button_id=B4GAXGG68L9MG
