name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main]

defaults:
  run:
    working-directory: .

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest, macos-12, macos-11]

    runs-on: ${{ matrix.os }}

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
    - name: Checkout repository # v4.0.0
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - name: Install PNPM # v2.4.0
      uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }} # v3.8.1
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    # All
    - name: (All) Install dependencies
      run: pnpm install
    - name: (All) Run All Tasks
      run: pnpm turbo all
